import { c, GRAIN } from './lib/tokens.js'

export const d = {
  panel: { display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden' },
  header: { display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: '12px', padding: '26px 26px 18px', borderBottom: `1px solid ${c.borderSoft}`, flexShrink: 0, flexWrap: 'wrap' },
  headerLeft: { flex: 1, minWidth: 0 },
  eyebrow: { fontFamily: c.mono, fontSize: '11px', color: c.faint, letterSpacing: '0.2em', textTransform: 'uppercase', marginBottom: '12px' },
  headlineRow: { display: 'flex', alignItems: 'baseline', gap: '12px', minWidth: 0 },
  methodLg: { fontFamily: c.mono, fontSize: '22px', flexShrink: 0, letterSpacing: '-0.5px' },
  pathLg: { fontSize: '22px', color: c.fg, fontWeight: 500, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontFamily: c.mono, letterSpacing: '-0.5px' },
  timestamp: { fontFamily: c.mono, fontSize: '11px', color: c.faint, flexShrink: 0 },
  meta: { display: 'flex', flexShrink: 0, borderBottom: `1px solid ${c.borderSoft}`, flexWrap: 'wrap' },
  metaItem: { display: 'flex', flexDirection: 'column', gap: '3px', padding: '10px 18px', borderRight: `1px solid ${c.borderSoft}` },
  metaLabel: { fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.18em', textTransform: 'uppercase' },
  metaVal: { fontSize: '12px', color: c.dim, fontFamily: c.mono },
  scroll: { flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column' },
  section: { padding: '16px 22px', borderBottom: `1px solid ${c.borderSoft}` },
  sectionTitle: { fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.2em', textTransform: 'uppercase', marginBottom: '12px' },
  bodyPre: { background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '6px', padding: '14px', fontSize: '12px', color: c.fg, fontFamily: c.mono, overflowX: 'auto', lineHeight: 1.6, whiteSpace: 'pre-wrap', wordBreak: 'break-word', flex: 1 },
  noSel: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: '8px', padding: '40px' },
  noSelText: { fontSize: '13px', color: c.dim },
  noSelSub: { fontSize: '12px', color: c.faint, textAlign: 'center', lineHeight: 1.6, maxWidth: '280px' },
  emptyWrap: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', padding: '40px' },
  emptyContent: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '18px', maxWidth: '480px', width: '100%' },
  emptyTitle: { fontSize: '17px', fontWeight: 500, color: c.fg },
  emptySub: { fontSize: '13.5px', color: c.dim, lineHeight: 1.6, marginTop: '-10px' },
  curlBlock: { width: '100%', border: `1px solid ${c.border}`, borderRadius: '8px', overflow: 'hidden' },
  curlLabel: { fontFamily: c.mono, fontSize: '10px', color: c.dim, letterSpacing: '0.2em', textTransform: 'uppercase' },
  curlCode: { padding: '14px', fontSize: '12px', color: c.fg, fontFamily: c.mono, lineHeight: 1.7, background: c.lowest, overflowX: 'auto', whiteSpace: 'pre' },
  curlHead: { padding: '8px 14px', background: c.low, borderBottom: `1px solid ${c.borderSoft}`, display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  curlCopyBtn: { display: 'flex', alignItems: 'center', gap: '5px', background: 'transparent', border: 'none', padding: '3px 7px', fontFamily: c.mono, fontSize: '10px', color: c.dim, cursor: 'pointer', borderRadius: '4px', letterSpacing: '0.06em', transition: 'background 0.12s, color 0.12s' },
  tips: { display: 'flex', flexDirection: 'column', gap: '7px' },
  tip: { fontSize: '12.5px', color: c.faint },
}

export const s = {
  shell: { height: '100vh', display: 'flex', background: c.bg, color: c.fg, fontFamily: c.sans, fontSize: '13px', overflow: 'hidden', position: 'relative' },
  grain: { position: 'fixed', inset: 0, zIndex: 0, pointerEvents: 'none', opacity: 0.02, backgroundImage: `url("${GRAIN}")`, backgroundSize: '200px' },

  rail: { position: 'relative', zIndex: 1, width: '48px', flexShrink: 0, background: c.low, borderRight: `1px solid ${c.borderSoft}`, display: 'flex', flexDirection: 'column', alignItems: 'center', paddingTop: '16px', gap: '4px' },
  railLogo: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '32px', height: '32px', marginBottom: '12px', borderRadius: '6px', background: c.accent, color: c.accentInk, fontFamily: c.sans, fontWeight: 600, fontSize: '16px', letterSpacing: '-0.5px', textDecoration: 'none', flexShrink: 0 },
  railDivider: { width: '20px', height: '1px', background: c.border, margin: '6px 0', flexShrink: 0 },
  railBtn: { position: 'relative', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '32px', height: '32px', borderRadius: '6px', background: 'transparent', border: 'none', color: c.faint, cursor: 'pointer', flexShrink: 0, transition: 'background 0.12s, color 0.12s' },
  railBtnActive: { background: c.high, color: c.fg },
  railBtnDot: { position: 'absolute', top: '4px', right: '4px', width: '6px', height: '6px', borderRadius: '50%', background: c.accent, boxShadow: `0 0 0 2px ${c.low}` },

  page: { position: 'relative', zIndex: 1, flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  pageHeader: { display: 'flex', flexDirection: 'column', gap: '12px', padding: '26px 26px 18px', borderBottom: `1px solid ${c.borderSoft}`, background: c.low, flexShrink: 0 },
  pageHeaderRow: { display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: '12px', flexWrap: 'wrap' },
  pageHeaderRight: { display: 'flex', alignItems: 'center', gap: '10px', justifyContent: 'flex-end', flexShrink: 0 },

  urlCard: { display: 'flex', alignItems: 'center', border: `1px solid ${c.border}`, borderRadius: '6px', overflow: 'hidden', background: c.bg, flexShrink: 1, minWidth: 0, maxWidth: '520px' },
  urlText: { flex: 1, fontFamily: c.mono, fontSize: '11.5px', color: c.dim, padding: '8px 12px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', minWidth: 0 },
  copyBtn: { display: 'flex', alignItems: 'center', justifyContent: 'center', background: c.ctr, border: 'none', borderLeft: `1px solid ${c.border}`, color: c.dim, padding: '8px 12px', cursor: 'pointer', flexShrink: 0 },

  copyTestBtn: { display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '8px 14px', background: 'transparent', border: `1px solid ${c.border}`, borderRadius: '6px', color: c.dim, fontFamily: c.sans, fontSize: '12px', cursor: 'pointer', transition: 'background 0.12s, border-color 0.12s, color 0.12s', flexShrink: 0 },

  masterPane: { width: '380px', flexShrink: 0, display: 'flex', flexDirection: 'column', borderRight: `1px solid ${c.borderSoft}`, overflow: 'hidden', minHeight: 0 },
  masterHeader: { padding: '12px 16px 8px', flexShrink: 0, borderBottom: `1px solid ${c.borderSoft}` },
  searchBox: { padding: '10px 14px 8px', flexShrink: 0 },

  listHead: { display: 'flex', alignItems: 'center', gap: '8px', padding: '4px 16px 6px', flexShrink: 0 },
  listHeadLabel: { fontFamily: c.mono, fontSize: '10px', fontWeight: 600, color: c.faint, letterSpacing: '0.2em', textTransform: 'uppercase', flex: 1 },
  listHeadCount: { fontFamily: c.mono, fontSize: '11px', color: c.dim },

  listRows: { flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '2px', padding: '6px 10px 10px', minHeight: 0 },
  listEmpty: { display: 'flex', alignItems: 'center', gap: '10px', padding: '16px 12px' },
  listEmptyText: { fontFamily: c.mono, fontSize: '11px', color: c.faint },

  detailPane: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', overflow: 'hidden' },

  pageBody: { flex: 1, overflow: 'auto', padding: '22px 26px', display: 'flex', flexDirection: 'column' },

  notFound: { height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: c.bg, fontFamily: c.sans, padding: '32px', color: c.fg, position: 'relative' },
  notFoundInner: { position: 'relative', zIndex: 1, display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '12px', maxWidth: '400px' },
  notFoundCode: { fontFamily: c.mono, fontSize: '12px', color: c.faint, letterSpacing: '0.2em' },
  notFoundTitle: { fontSize: '22px', fontWeight: 500, color: c.fg },
  notFoundSub: { fontSize: '13.5px', color: c.dim, lineHeight: 1.6 },
  notFoundBtn: { display: 'inline-block', marginTop: '8px', padding: '10px 18px', fontFamily: c.sans, fontWeight: 500, fontSize: '13px', color: c.accentInk, borderRadius: '4px', textDecoration: 'none', background: c.accent },
}

export const rc = {
  section:      { display: 'flex', flexDirection: 'column', gap: '14px', maxWidth: '760px' },
  sectionHead:  { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px', flexWrap: 'wrap' },
  sectionTitle: { fontFamily: c.mono, fontSize: '10px', fontWeight: 600, color: c.faint, letterSpacing: '0.22em', textTransform: 'uppercase' },
  pillOn:       { display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: c.mono, fontSize: '10px', color: c.accent, letterSpacing: '0.04em', padding: '3px 8px', borderRadius: '999px', border: `1px solid ${c.border}`, background: c.bg },
  pillOnDot:    { width: '5px', height: '5px', borderRadius: '50%', background: c.accent },
  pillOff:      { fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.04em', padding: '3px 8px', borderRadius: '999px', border: `1px solid ${c.border}`, background: c.bg },
  card:         { padding: '16px', border: `1px solid ${c.border}`, borderRadius: '8px', background: c.bg, display: 'flex', flexDirection: 'column', gap: '14px' },
  field:        { display: 'flex', flexDirection: 'column', gap: '6px' },
  fieldRow:     { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px' },
  label:        { fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.18em', textTransform: 'uppercase' },
  select:       { background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '6px', color: c.fg, fontFamily: c.mono, fontSize: '12px', padding: '9px 12px', outline: 'none', width: '100%' },
  input:        { background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '6px', color: c.fg, fontFamily: c.mono, fontSize: '12px', padding: '9px 12px', outline: 'none', width: '100%' },
  inputOver:    { borderColor: 'var(--status-red)' },
  textarea:     { background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '6px', color: c.fg, fontFamily: c.mono, fontSize: '12px', padding: '12px 14px', minHeight: '120px', resize: 'vertical', outline: 'none', lineHeight: 1.55, width: '100%' },
  switchRow:    { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px', background: 'transparent', border: `1px solid ${c.border}`, borderRadius: '6px', padding: '12px 14px', cursor: 'pointer', width: '100%', textAlign: 'left' },
  switchRowLabel:{ fontFamily: c.sans, fontSize: '13px', color: c.fg, fontWeight: 500 },
  switchHint:   { fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.06em' },
  switchTrack:  { width: '32px', height: '18px', background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '999px', position: 'relative', transition: 'background 0.15s, border-color 0.15s', flexShrink: 0 },
  switchTrackOn:{ background: c.accentInk, borderColor: c.accent },
  switchThumb:  { position: 'absolute', top: '1px', left: '1px', width: '14px', height: '14px', borderRadius: '50%', background: c.dim, transition: 'transform 0.15s, background 0.15s' },
  switchThumbOn:{ transform: 'translateX(14px)', background: c.accent },
  btnRow:       { display: 'flex', gap: '8px', flexWrap: 'wrap' },
  btnPrimary:   { background: c.accent, color: c.accentInk, border: 'none', borderRadius: '6px', padding: '9px 18px', fontFamily: c.sans, fontSize: '13px', fontWeight: 500, cursor: 'pointer' },
  btnGhost:     { background: 'transparent', color: c.dim, border: `1px solid ${c.border}`, borderRadius: '6px', padding: '9px 18px', fontFamily: c.sans, fontSize: '13px', cursor: 'pointer' },
  scriptCount:  { fontFamily: c.mono, fontSize: '10px', color: c.faint, textAlign: 'right' },
  scriptCountOver: { fontFamily: c.mono, fontSize: '10px', color: 'var(--status-red)', textAlign: 'right' },
  error:        { fontSize: '12px', color: 'var(--status-red)', fontFamily: c.mono },
}

export const md = {
  backdrop:    { position: 'fixed', inset: 0, zIndex: 100, background: 'rgba(0,0,0,0.55)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px', backdropFilter: 'blur(2px)' },
  box:         { background: c.bg, border: `1px solid ${c.border}`, borderRadius: '10px', padding: '22px', maxWidth: '460px', width: '100%', display: 'flex', flexDirection: 'column', gap: '14px', boxShadow: '0 24px 60px rgba(0,0,0,0.45)' },
  title:       { fontFamily: c.sans, fontSize: '15px', fontWeight: 500, color: c.fg },
  body:        { fontFamily: c.sans, fontSize: '13px', color: c.dim, lineHeight: 1.55 },
  bodyMono:    { fontFamily: c.mono, fontSize: '11px', color: c.fg, background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '4px', padding: '8px 10px', wordBreak: 'break-all' },
  actions:     { display: 'flex', justifyContent: 'flex-end', gap: '8px', marginTop: '4px' },
}

export const fr = {
  section:     { display: 'flex', flexDirection: 'column', gap: '14px', maxWidth: '760px' },
  pill:        { display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.04em', padding: '3px 8px', borderRadius: '999px', border: `1px solid ${c.border}`, background: c.bg },
  pillOk:      { color: c.accent },
  pillDot:     { width: '5px', height: '5px', borderRadius: '50%', background: c.accent },
  statusRow:   { display: 'flex', alignItems: 'center', gap: '10px', fontFamily: c.mono, fontSize: '12px', color: c.dim },
  statusOk:    { display: 'inline-flex', alignItems: 'center', padding: '2px 7px', borderRadius: '3px', background: c.low, border: `1px solid ${c.border}`, color: c.fg, fontSize: '10px' },
  statusErr:   { display: 'inline-flex', alignItems: 'center', padding: '2px 7px', borderRadius: '3px', background: 'var(--status-red-bg, transparent)', border: `1px solid var(--status-red, ${c.border})`, color: 'var(--status-red)', fontSize: '10px' },
  pre:         { background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '6px', padding: '14px', fontSize: '12px', color: c.fg, fontFamily: c.mono, overflowX: 'auto', lineHeight: 1.55, whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0 },
  meta:        { display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap', fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.04em' },
  metaKey:     { color: c.dim },
}

export const mc = {
  section:      { display: 'flex', flexDirection: 'column', gap: '20px', maxWidth: '820px' },
  card:         { padding: '18px', border: `1px solid ${c.border}`, borderRadius: '8px', background: c.bg, display: 'flex', flexDirection: 'column', gap: '14px' },
  cardTitle:    { fontFamily: c.mono, fontSize: '10px', fontWeight: 600, color: c.faint, letterSpacing: '0.22em', textTransform: 'uppercase' },
  mcpHint:      { fontSize: '13px', color: c.dim, lineHeight: 1.55, fontFamily: c.sans, margin: 0 },
  urlRow:       { display: 'flex', alignItems: 'stretch', border: `1px solid ${c.border}`, borderRadius: '6px', overflow: 'hidden', background: c.lowest },
  urlText:      { flex: 1, fontFamily: c.mono, fontSize: '13px', color: c.fg, padding: '12px 14px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', minWidth: 0 },
  tokenRow:     { display: 'flex', alignItems: 'stretch', border: `1px solid ${c.border}`, borderRadius: '6px', overflow: 'hidden', background: c.lowest },
  tokenText:    { flex: 1, fontFamily: c.mono, fontSize: '13px', color: c.fg, padding: '12px 14px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', minWidth: 0, letterSpacing: '0.02em' },
  tokenCopy:    { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px', background: c.ctr, border: 'none', borderLeft: `1px solid ${c.border}`, color: c.dim, padding: '0 16px', cursor: 'pointer', flexShrink: 0, fontFamily: c.mono, fontSize: '11px', letterSpacing: '0.06em' },
  curlBlock:    { border: `1px solid ${c.border}`, borderRadius: '6px', overflow: 'hidden' },
  curlHead:     { padding: '8px 14px', background: c.low, borderBottom: `1px solid ${c.borderSoft}`, fontFamily: c.mono, fontSize: '10px', color: c.dim, letterSpacing: '0.18em', textTransform: 'uppercase' },
  curlCode:     { padding: '14px', fontSize: '12px', color: c.fg, fontFamily: c.mono, lineHeight: 1.65, background: c.lowest, overflowX: 'auto', whiteSpace: 'pre', margin: 0 },
  configGroup:  { borderBottom: `1px solid ${c.borderSoft}` },
  configHead:   { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 14px', background: c.low, borderBottom: `1px solid ${c.borderSoft}` },
  configLabel:  { fontFamily: c.mono, fontSize: '10px', color: c.dim, letterSpacing: '0.18em', textTransform: 'uppercase' },
  configCode:   { padding: '14px', fontSize: '12px', color: c.fg, fontFamily: c.mono, lineHeight: 1.65, background: c.lowest, overflowX: 'auto', whiteSpace: 'pre', margin: 0 },
  actionRow:    { display: 'flex', alignItems: 'center', gap: '14px', flexWrap: 'wrap' },
  mintBtn:      { display: 'inline-flex', alignItems: 'center', gap: '6px', background: 'transparent', border: `1px dashed ${c.border}`, borderRadius: '6px', color: c.dim, padding: '8px 14px', fontFamily: c.mono, fontSize: '11px', letterSpacing: '0.04em', cursor: 'pointer', transition: 'border-color 0.12s, color 0.12s' },
  mintBtnDisabled: { opacity: 0.5, cursor: 'wait' },
  emptyMsg:     { fontSize: '13px', color: c.dim, lineHeight: 1.55, fontFamily: c.sans, margin: 0 },
  footer:       { fontFamily: c.mono, fontSize: '11px', color: c.faint, letterSpacing: '0.06em', margin: 0 },
  footerInbox:  { color: c.dim, marginLeft: '6px' },
  err:          { fontSize: '12px', color: 'var(--status-red)', fontFamily: c.mono },
}

export const sc = {
  section:      { display: 'flex', flexDirection: 'column', gap: '20px', maxWidth: '960px' },
  card:         { padding: '18px', border: `1px solid ${c.border}`, borderRadius: '8px', background: c.bg, display: 'flex', flexDirection: 'column', gap: '14px' },
  cardHead:     { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px' },
  cardTitle:    { fontFamily: c.mono, fontSize: '10px', fontWeight: 600, color: c.faint, letterSpacing: '0.22em', textTransform: 'uppercase' },
  cardMeta:     { fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.04em' },
  table:        { display: 'flex', flexDirection: 'column' },
  tableHead:    { display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 90px 70px 100px', gap: '12px', padding: '6px 14px', fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.16em', textTransform: 'uppercase', borderBottom: `1px solid ${c.borderSoft}` },
  tableRow:     { display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 90px 70px 100px', gap: '12px', padding: '9px 14px', borderBottom: `1px solid ${c.borderSoft}`, alignItems: 'center', fontFamily: c.mono, fontSize: '12px' },
  tableRowLast: { borderBottom: 'none' },
  pathMono:     { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', minWidth: 0, color: c.dim },
  typeTag:      { display: 'inline-flex', alignItems: 'center', justifyContent: 'flex-start', fontFamily: c.mono, fontSize: '10px', padding: '2px 7px', borderRadius: '3px', background: c.low, color: c.fg, border: `1px solid ${c.border}`, width: 'fit-content' },
  countMono:    { color: c.faint },
  empty:        { padding: '40px', textAlign: 'center', fontFamily: c.mono, fontSize: '12px', color: c.faint },
}
