import { c, GRAIN } from './lib/tokens.js'

export const d = {
  panel: { display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden' },
  header: { display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: '12px', padding: '26px 26px 18px', borderBottom: `1px solid ${c.borderSoft}`, flexShrink: 0, flexWrap: 'wrap' },
  headerLeft: { flex: 1, minWidth: 0 },
  eyebrow: { fontFamily: c.mono, fontSize: '11px', color: c.faint, letterSpacing: '0.2em', textTransform: 'uppercase', marginBottom: '12px' },
  headlineRow: { display: 'flex', alignItems: 'baseline', gap: '12px', minWidth: 0 },
  methodLg: { fontFamily: c.mono, fontSize: '22px', flexShrink: 0, letterSpacing: '-0.5px' },
  pathLg: { fontSize: '22px', color: c.fg, fontWeight: 500, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontFamily: c.mono, letterSpacing: '-0.5px' },
  timestamp: { fontFamily: c.mono, fontSize: '11px', color: c.faint, flexShrink: 0 },
  meta: { display: 'flex', flexShrink: 0, borderBottom: `1px solid ${c.borderSoft}`, flexWrap: 'wrap' },
  metaItem: { display: 'flex', flexDirection: 'column', gap: '3px', padding: '10px 18px', borderRight: `1px solid ${c.borderSoft}` },
  metaLabel: { fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.18em', textTransform: 'uppercase' },
  metaVal: { fontSize: '12px', color: c.dim, fontFamily: c.mono },
  scroll: { flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column' },
  section: { padding: '16px 22px', borderBottom: `1px solid ${c.borderSoft}` },
  sectionTitle: { fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.2em', textTransform: 'uppercase', marginBottom: '12px' },
  bodyPre: { background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '6px', padding: '14px', fontSize: '12px', color: c.fg, fontFamily: c.mono, overflowX: 'auto', lineHeight: 1.6, whiteSpace: 'pre-wrap', wordBreak: 'break-word', flex: 1 },
  noSel: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: '8px', padding: '40px' },
  noSelText: { fontSize: '13px', color: c.dim },
  noSelSub: { fontSize: '12px', color: c.faint, textAlign: 'center', lineHeight: 1.6, maxWidth: '280px' },
  emptyWrap: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', padding: '40px' },
  emptyContent: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '18px', maxWidth: '480px', width: '100%' },
  emptyTitle: { fontSize: '17px', fontWeight: 500, color: c.fg },
  emptySub: { fontSize: '13.5px', color: c.dim, lineHeight: 1.6, marginTop: '-10px' },
  curlBlock: { width: '100%', border: `1px solid ${c.border}`, borderRadius: '8px', overflow: 'hidden' },
  curlLabel: { fontFamily: c.mono, fontSize: '10px', color: c.dim, letterSpacing: '0.2em', textTransform: 'uppercase' },
  curlCode: { padding: '14px', fontSize: '12px', color: c.fg, fontFamily: c.mono, lineHeight: 1.7, background: c.lowest, overflowX: 'auto', whiteSpace: 'pre' },
  curlHead: { padding: '8px 14px', background: c.low, borderBottom: `1px solid ${c.borderSoft}`, display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  curlCopyBtn: { display: 'flex', alignItems: 'center', gap: '5px', background: 'transparent', border: 'none', padding: '3px 7px', fontFamily: c.mono, fontSize: '10px', color: c.dim, cursor: 'pointer', borderRadius: '4px', letterSpacing: '0.06em', transition: 'background 0.12s, color 0.12s' },
  tips: { display: 'flex', flexDirection: 'column', gap: '7px' },
  tip: { fontSize: '12.5px', color: c.faint },
}

export const s = {
  shell: { height: '100vh', display: 'flex', background: c.bg, color: c.fg, fontFamily: c.sans, fontSize: '13px', overflow: 'hidden', position: 'relative' },
  grain: { position: 'fixed', inset: 0, zIndex: 0, pointerEvents: 'none', opacity: 0.02, backgroundImage: `url("${GRAIN}")`, backgroundSize: '200px' },

  sidebar: { position: 'relative', zIndex: 1, width: '272px', flexShrink: 0, background: c.low, borderRight: `1px solid ${c.borderSoft}`, display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  logo: { padding: '38px 24px 22px', flexShrink: 0 },
  logoText: { fontFamily: c.sans, fontSize: '28px', fontWeight: 500, letterSpacing: '-1px', color: c.fg, textDecoration: 'none' },
  ctxRow: { display: 'flex', alignItems: 'center', gap: '10px', margin: '0 12px 12px', padding: '10px 12px', borderRadius: '8px', flexShrink: 0 },
  ctxIcon: { fontSize: '18px', color: c.faint, flexShrink: 0 },
  ctxName: { flex: 1, fontFamily: c.sans, fontSize: '14px', color: c.dim },

  urlCard: { display: 'flex', alignItems: 'center', margin: '0 12px 14px', border: `1px solid ${c.border}`, borderRadius: '6px', overflow: 'hidden', background: c.bg, flexShrink: 0 },
  urlText: { flex: 1, fontFamily: c.mono, fontSize: '11px', color: c.dim, padding: '8px 10px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', minWidth: 0 },
  copyBtn: { display: 'flex', alignItems: 'center', justifyContent: 'center', background: c.ctr, border: 'none', borderLeft: `1px solid ${c.border}`, color: c.dim, padding: '8px 11px', cursor: 'pointer', flexShrink: 0 },

  copyTestBtn: { display: 'flex', alignItems: 'center', gap: '8px', margin: '0 12px 12px', padding: '7px 10px', background: 'transparent', border: `1px solid ${c.border}`, borderRadius: '6px', color: c.dim, fontFamily: c.sans, fontSize: '12px', cursor: 'pointer', transition: 'background 0.12s, border-color 0.12s, color 0.12s' },

  listHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 20px 8px', flexShrink: 0 },
  listHeadLabel: { fontFamily: c.mono, fontSize: '10px', fontWeight: 600, color: c.faint, letterSpacing: '0.2em', textTransform: 'uppercase' },
  listHeadCount: { fontFamily: c.mono, fontSize: '11px', color: c.dim },
  listRows: { flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '2px', padding: '0 8px 8px', minHeight: 0 },
  listEmpty: { display: 'flex', alignItems: 'center', gap: '10px', padding: '16px 12px' },
  listEmptyText: { fontFamily: c.mono, fontSize: '11px', color: c.faint },

  sidebarBottom: { padding: '14px 12px', borderTop: `1px solid ${c.borderSoft}`, display: 'flex', flexDirection: 'column', gap: '8px', flexShrink: 0 },
  ctaBtn: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px', fontFamily: c.sans, fontWeight: 500, fontSize: '13px', color: c.accentInk, borderRadius: '6px', padding: '9px 14px', textDecoration: 'none', background: c.accent },
  ctaCaption: { fontSize: '11px', color: c.faint, lineHeight: 1.5, padding: '0 2px' },

  content: { position: 'relative', zIndex: 1, flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column', minWidth: 0 },
  notFound: { height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: c.bg, fontFamily: c.sans, padding: '32px', color: c.fg, position: 'relative' },
  notFoundInner: { position: 'relative', zIndex: 1, display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '12px', maxWidth: '400px' },
  notFoundCode: { fontFamily: c.mono, fontSize: '12px', color: c.faint, letterSpacing: '0.2em' },
  notFoundTitle: { fontSize: '22px', fontWeight: 500, color: c.fg },
  notFoundSub: { fontSize: '13.5px', color: c.dim, lineHeight: 1.6 },
  notFoundBtn: { display: 'inline-block', marginTop: '8px', padding: '10px 18px', fontFamily: c.sans, fontWeight: 500, fontSize: '13px', color: c.accentInk, borderRadius: '4px', textDecoration: 'none', background: c.accent },
}

export const rc = {
  wrap:       { margin: '0 12px 14px', padding: '12px', border: `1px solid ${c.border}`, borderRadius: '6px', background: c.bg, flexShrink: 0, display: 'flex', flexDirection: 'column', gap: '8px', transition: 'padding 0.15s ease' },
  headBtn:    { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '8px', background: 'transparent', border: 'none', padding: '2px 0', cursor: 'pointer', borderRadius: '4px', width: '100%', textAlign: 'left' },
  headLeft:   { display: 'flex', alignItems: 'center', gap: '8px', minWidth: 0 },
  chev:       { fontSize: '16px', color: c.faint, flexShrink: 0, transition: 'color 0.12s' },
  title:      { fontFamily: c.mono, fontSize: '10px', fontWeight: 600, color: c.faint, letterSpacing: '0.2em', textTransform: 'uppercase' },
  pillOn:     { display: 'inline-flex', alignItems: 'center', gap: '6px', fontFamily: c.mono, fontSize: '10px', color: c.accent, letterSpacing: '0.04em' },
  pillOnDot:  { width: '5px', height: '5px', borderRadius: '50%', background: c.accent },
  pillOff:    { fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.04em' },
  switchRow:    { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '8px', background: 'transparent', border: 'none', padding: '2px 0', cursor: 'pointer', width: '100%', textAlign: 'left' },
  switchRowLabel:{ fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.2em', textTransform: 'uppercase' },
  switchTrack:  { width: '28px', height: '16px', background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '999px', position: 'relative', transition: 'background 0.15s, border-color 0.15s', flexShrink: 0 },
  switchTrackOn:{ background: c.accentInk, borderColor: c.accent },
  switchThumb:  { position: 'absolute', top: '1px', left: '1px', width: '12px', height: '12px', borderRadius: '50%', background: c.dim, transition: 'transform 0.15s, background 0.15s' },
  switchThumbOn:{ transform: 'translateX(12px)', background: c.accent },
  label:        { fontFamily: c.mono, fontSize: '10px', color: c.faint, letterSpacing: '0.12em', textTransform: 'uppercase', marginTop: '2px' },
  select:     { background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '4px', color: c.fg, fontFamily: c.mono, fontSize: '11px', padding: '6px 8px', outline: 'none' },
  textarea:   { background: c.lowest, border: `1px solid ${c.border}`, borderRadius: '4px', color: c.fg, fontFamily: c.mono, fontSize: '11px', padding: '8px', minHeight: '64px', resize: 'vertical', outline: 'none', lineHeight: 1.5 },
  btnRow:     { display: 'flex', gap: '6px', marginTop: '4px' },
  btnPrimary: { flex: 1, background: c.accent, color: c.accentInk, border: 'none', borderRadius: '4px', padding: '7px 10px', fontFamily: c.sans, fontSize: '12px', fontWeight: 500, cursor: 'pointer' },
  btnGhost:   { background: 'transparent', color: c.dim, border: `1px solid ${c.border}`, borderRadius: '4px', padding: '7px 10px', fontFamily: c.sans, fontSize: '12px', cursor: 'pointer' },
  error:      { fontSize: '11px', color: 'var(--status-red)', fontFamily: c.mono, marginTop: '2px' },
}
